### PR TITLE
Rebuild for libboost 1.86 with backport of upstream PR 43 and add traversaro to maintainers

### PR DESCRIPTION
**Pull request by traversaro**
Based on https://github.com/conda-forge/collada-dom-feedstock/pull/12 with the additional backport of https://github.com/rdiankov/collada-dom/pull/43, see https://github.com/rdiankov/collada-dom/issues/42 for more info.

@conda-forge/collada-dom @jcarpent @h-vetinari given that this is in the dependency path of dart/gazebo, I am happy to be mantainer here.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Review by jcarpent — APPROVED** [review]

**Comment by h-vetinari** [comment]
👍 great thanks!

**Comment by traversaro** [comment]
@jcarpent @h-vetinari CI ended successfully, I think this is ready for merge, thanks!

**Comment by h-vetinari** [comment]
Given @jcarpent's approval, I'm going ahead with the merge here to allow the migration to proceed. :)

**Pull request merged**
